### PR TITLE
Git submodule dto

### PR DESCRIPTION
**Pull request by dima618**
Added submodule for DTOs and entities

### CODE REVIEW

**Comment by smalhotra3599** [comment]
I looked through the peer-recognition-dto repo and noticed the entities and dtos but I didn't see any enums. Can we also move the role enum (and any others we may have) to the submodule as well?

**Comment by smalhotra3599** [comment]
@dima618 I looked through the peer-recognition-dto repo and noticed the entities and dtos but I didn't see any enums. Can we also move the role enum (and any others we may have) to the submodule as well?

**Comment by dima618** [comment]
I added the rest of the enums I could find to the submodule and deleted them from our current repo.

**Comment by smalhotra3599** [comment]
@dima618 can you merge master into this branch to resolve merge conflicts and then work with the backend team to get this merged **ASAP**? This is causing issues with future work where entity changes are being made within the backend repo instead of the dto repo. @jarodroto @jeremydrn @nghiaphamumass @cubscout61 @matt-weiner please be aware of this for all future work - entity changes will need to go in the dto submodule repo.

**Review by jeremydrn — APPROVED** [review]

**Pull request merged**
